language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  slack: $SLACK_TOKEN
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
  - yarn stylus
  - echo 'anabelisa.co' > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop